from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .utils import print_json, write_json_file


def load_tokens(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def doctor(args: argparse.Namespace) -> int:
    data = {"tool": "toolkit-design", "status": "ok", "python": sys.version.split()[0]}
    print_json(data) if args.json else print("toolkit-design doctor: ok")
    return 0


def validate(args: argparse.Namespace) -> int:
    token_file = Path(args.token_file)
    data = load_tokens(token_file)
    issues = []
    if not isinstance(data, dict):
        issues.append("root_must_be_object")
    payload = {"token_file": str(token_file), "issues": issues, "status": "ok" if not issues else "has_issues"}
    print_json(payload) if args.json else print(f"Validated {token_file}")
    return 0 if not issues else 1


def map_tokens(args: argparse.Namespace) -> int:
    token_file = Path(args.token_file)
    data = load_tokens(token_file)
    mapped = {"groups": sorted(list(data.keys())) if isinstance(data, dict) else []}
    print_json(mapped) if args.json else print(f"Mapped {token_file}")
    return 0


def export_tokens(args: argparse.Namespace) -> int:
    token_file = Path(args.token_file)
    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    data = load_tokens(token_file)
    out = out_dir / "normalized_tokens.json"
    write_json_file(out, data)
    payload = {"output": str(out)}
    print_json(payload) if args.json else print(f"Exported to {out}")
    return 0


def flutter_sync(args: argparse.Namespace) -> int:
    token_file = Path(args.token_file)
    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    data = load_tokens(token_file)
    dart_path = out_dir / "design_tokens.g.dart"
    dart_content = [
        "// Generated by toolkit-design",
        "class DesignTokens {",
    ]
    if isinstance(data, dict):
        for group, values in data.items():
            dart_content.append(f"  // group: {group}")
    dart_content.append("}")
    dart_path.write_text("\n".join(dart_content) + "\n", encoding="utf-8")
    payload = {"output": str(dart_path)}
    print_json(payload) if args.json else print(f"Flutter sync wrote {dart_path}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="toolkit-design")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("doctor")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=doctor)

    p = sub.add_parser("validate")
    p.add_argument("token_file")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=validate)

    p = sub.add_parser("map")
    p.add_argument("token_file")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=map_tokens)

    p = sub.add_parser("export")
    p.add_argument("token_file")
    p.add_argument("--output", required=True)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=export_tokens)

    p = sub.add_parser("flutter-sync")
    p.add_argument("token_file")
    p.add_argument("--output", required=True)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=flutter_sync)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
